ecommerce_cosmetika/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('profile/', views.profile, name='profile'),
]

ecommerce_cosmetika/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:product_id>/', views.cart_add, name='cart_update'),
]

ecommerce_cosmetika/ecommerce_cosmetika/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce_cosmetika/products/urls.py
from django.urls import path
from . import views

app_name = 'products'

urlpatterns = [
    path('', views.index, name='index'),
]

urls.py
import django
from django.apps import apps
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import views
from django.urls import include, path
from oscar.views import handler403, handler404, handler500

from apps.sitemaps import base_sitemaps

admin.autodiscover()

urlpatterns = [
    # Include admin as convenience. It's unsupported and only included
    # for developers.
    path('admin/', admin.site.urls),

    # i18n URLS need to live outside of i18n_patterns scope of Oscar
    path('i18n/', include(django.conf.urls.i18n)),

    # include a basic sitemap
    path('sitemap.xml', views.index,
        {'sitemaps': base_sitemaps}),
    path('sitemap-<slug:section>.xml', views.sitemap,
        {'sitemaps': base_sitemaps},
        name='django.contrib.sitemaps.views.sitemap')
]

# Prefix Oscar URLs with language codes
urlpatterns += i18n_patterns(
    path('', include(apps.get_app_config('oscar').urls[0])),
)

if settings.DEBUG:
    import debug_toolbar

    # Server statics and uploaded media
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    # Allow error pages to be tested
    urlpatterns += [
        path('403', handler403, {'exception': Exception()}),
        path('404', handler404, {'exception': Exception()}),
        path('500', handler500),
        path('__debug__/', include(debug_toolbar.urls)),
    ]

apps/user/models.py
"""
Sample user/profile models for testing.  These aren't enabled by default in the
sandbox
"""

from django.contrib.auth.models import (
    AbstractUser, BaseUserManager, AbstractBaseUser)
from django.db import models
from django.utils import timezone

from oscar.core import compat
from oscar.apps.customer import abstract_models


class Profile(models.Model):
    """
    Dummy profile model used for testing
    """
    user = models.OneToOneField(compat.AUTH_USER_MODEL, related_name="profile",
                                on_delete=models.CASCADE)
    MALE, FEMALE = 'M', 'F'
    choices = (
        (MALE, 'Male'),
        (FEMALE, 'Female'))
    gender = models.CharField(max_length=1, choices=choices,
                              verbose_name='Gender')
    age = models.PositiveIntegerField(verbose_name='Age')


# A simple extension of the core User model for Django 1.5+
class ExtendedUserModel(AbstractUser):
    twitter_username = models.CharField(max_length=255, unique=True)


class CustomUserManager(BaseUserManager):

    def create_user(self, email, password=None):
        now = timezone.now()
        email = BaseUserManager.normalize_email(email)
        user = self.model(email=email, last_login=now)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password):
        return self.create_user(email, password)

# A user model which doesn't extend AbstractUser
class CustomUserModel(AbstractBaseUser):
    name = models.CharField(max_length=255, blank=True)
    email = models.EmailField(unique=True)
    twitter_username = models.CharField(max_length=255, unique=True)

    USERNAME_FIELD = 'email'

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def get_full_name(self):
        return self.name

    get_short_name = get_full_name

# A simple extension of the core Oscar User model
class ExtendedOscarUserModel(abstract_models.AbstractUser):
    twitter_username = models.CharField(max_length=255, unique=True)

carga/models.py
from django.db import models
from .csv_importer import import_products_from_csv


class CSV(models.Model):
    nombre = models.CharField(max_length=255)
    archivo = models.FileField(upload_to='csv_subidos/')
    fecha_carga = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombre
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        import_products_from_csv(self.archivo.path)

ecommerce_cosmetika/accounts/models.py
from django.db import models

# Create your models here.

ecommerce_cosmetika/cart/models.py
from django.db import models

# Create your models here.

ecommerce_cosmetika/products/models.py
from django.db import models

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/')
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

ecommerce_cosmetika/cart/forms.py
from django import forms

class CartAddProductForm(forms.Form):
    quantity = forms.IntegerField(min_value=1, widget=forms.NumberInput(attrs={'class': 'form-control'}))
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

carga/views.py
from django.shortcuts import render

# Create your views here.

ecommerce_cosmetika/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('products:index')
    else:
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})

@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

ecommerce_cosmetika/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from products.models import Product
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], update_quantity=cd['update'])
    return redirect('cart:cart_detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})

ecommerce_cosmetika/products/views.py
from django.shortcuts import render
from .models import Product
from cart.forms import CartAddProductForm

# Create your views here.

def index(request):
    products = Product.objects.all()
    context = {'products': products}
    context = {'products': products, 'form': CartAddProductForm()}
    return render(request, 'products/index.html', context)

ecommerce_cosmetika/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
  <h2>Página de perfil</h2>
  <p>Bienvenido, {{ user.username }}.</p>
{% endblock %}

ecommerce_cosmetika/cart/templates/cart/detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Carrito de compras</h1>
    {% for item in cart %}
        <div class="cart-item">
            <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}">
            <h2>{{ item.product.name }}</h2>
            <form action="{% url 'cart:cart_update' item.product.id %}" method="post">
                {% csrf_token %}
                {{ form.quantity }}
                <input type="submit" value="Actualizar">
                <input type="hidden" name="update" value="True">
            </form>
            <p>${{ item.total_price }}</p>
            <a href="{% url 'cart:cart_remove' item.product.id %}">Eliminar</a>
        </div>
    {% endfor %}
    <p>Total: ${{ cart.get_total_price }}</p>
{% endblock %}

ecommerce_cosmetika/products/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Ecommerce Cosmetika</title>
    <!-- Añadir tus archivos CSS y JS aquí -->
</head>
<body>
    <header>
        <!-- Añadir la navegación y el encabezado aquí -->
    </header>

    <main>
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <!-- Añadir el pie de página aquí -->
    </footer>
</body>
</html>

ecommerce_cosmetika/products/templates/products/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Productos</h1>
    <div class="product-grid">
        {% for product in products %}
            <div class="product">
                <img src="{{ product.image.url }}" alt="{{ product.name }}">
                <h2>{{ product.name }}</h2>
                <p>{{ product.description|truncatechars:100 }}</p>
                <p>${{ product.price }}</p>
            </div>
	    <form action="{% url 'cart:cart_add' product.id %}" method="post">
             {% csrf_token %}
             {{ form.quantity }}
             <input type="submit" value="Añadir al carrito">
            </form>
        {% endfor %}
    </div>
{% endblock %}